services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: cloud_sre
      POSTGRES_USER: leanhduc
      POSTGRES_PASSWORD: anhdc2005

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: leanhduc2005
      RABBITMQ_DEFAULT_PASS: leanhduc2005_rabbit
    ports:
      - "15672:15672"
      - "5672:5672"

  redis:
    image: redis:7

  user:
    build: services/user
    ports:
      - "3001:3000"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: leanhduc
      POSTGRES_PASSWORD: anhdc2005
      JWT_SECRET_KEY: anhducjwt

  auth:
    build: services/auth
    ports:
      - "3004:3000"
    environment:
      JWT_SECRET_KEY: anhducjwt

  order:
    build: services/order
    ports:
      - "3002:3000"
    environment:
      USER_SERVICE_URL: http://user:3000
      RABBIT_URL: amqp://leanhduc2005:leanhduc2005_rabbit@rabbitmq:5672/

  payment:
    build: services/payment
    ports:
      - "3003:3000"

  cart:
    build: services/cart
    ports:
      - "3005:3000"

  product:
    build: services/product
    ports:
      - "3006:3000"

  notification:
    build: services/notification
    environment:
      RABBIT_URL: amqp://leanhduc2005:leanhduc2005_rabbit@rabbitmq:5672/
    depends_on:
      - rabbitmq
