CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL
);

INSERT INTO users (name) 
SELECT 'SRE User 1' WHERE NOT EXISTS (SELECT 1 FROM users WHERE name = 'SRE User 1');

INSERT INTO users (name) 
SELECT 'SRE User 2' WHERE NOT EXISTS (SELECT 1 FROM users WHERE name = 'SRE User 2');
