worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=10r/s;

    server {
        listen       80;
        server_name  localhost;

        location /auth {
            limit_req zone=api_limit burst=10;
            proxy_pass http://auth:3000;
        }

        location /users {
            proxy_pass http://user:3000;
        }

        location /products {
            proxy_pass http://product:3000;
        }

        location /cart {
            proxy_pass http://cart:3000;
        }

        location /orders {
            proxy_pass http://order:3000;
        }

        location /pay {
            proxy_pass http://payment:3000;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
}
