apiVersion: v1
kind: ConfigMap
metadata:
  name: cloud-sre-config
data:
  RABBIT_URL: "amqp://guest:guest@rabbitmq:5672/"
  USER_SERVICE_URL: "http://user:3000"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  DB_HOST: "postgres"
  DB_PORT: "5432"
