apiVersion: v1
kind: Secret
metadata:
  name: cloud-sre-secrets
type: Opaque
stringData:
  POSTGRES_USER: leanhduc
  POSTGRES_PASSWORD: anhdc2005
  RABBITMQ_USER: leanhduc2005
  RABBITMQ_PASS: leanhduc2005_rabbit
  JWT_SECRET_KEY: anhducjwt
  auth: leanhduc:$apr1$a1$jiWqt6erGsH.ZSCCsk9.mS0
  RABBITMQ_URL: amqp://leanhduc2005:leanhduc2005_rabbit@rabbitmq:5672/
